### ISSUE TITLE
Pagination not working?

### ISSUE THREAD

**Issue by winkler1** [roman01la/github-issues#1]
Hi-
 When I go to https://romanliutikov.com/github-issues/, and do user:facebook, repo react, it fetches ok. Clicking Next changes page # to 2, but the list does not update.

**Comment by roman01la** [comment]
@winkler1 Any errors in the console? What browser?

**Comment by winkler1** [comment]
Chrome...nope, no errors...

Hmmm, just visited again and the glitch is not happening... also it's showing stars and followers and description where it didn't the first time. <Shrug/>, guess I'll have to redo the screenshot at http://react.rocks/example/github-issues

thanks
